# Generated by Django 5.1.5 on 2025-02-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='TaskList',
        ),
    ]
